
version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=1234qwer 
      - xpack.security.enabled=true  # Enable security if needed, but disable SSL
      - xpack.security.transport.ssl.enabled=false  # Disable SSL for transport layer
      - xpack.security.http.ssl.enabled=false  # Disable SSL for HTTP layer
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  fluentd:
    image: fluent/fluentd:v1.14-1
    container_name: fluentd
    environment:
      - FLUENT_ELASTICSEARCH_HOST=elasticsearch
      - FLUENT_ELASTICSEARCH_PORT=9200
      - FLUENT_ELASTICSEARCH_USER=james  # Provide Elasticsearch username
      - FLUENT_ELASTICSEARCH_PASSWORD=1234qwer  # Provide Elasticsearch password
    volumes:
      - ./fluentd/conf/fluentd.conf:/fluentd/etc/fluentd.conf  # Fluentd 配置文件
      - ../src/ELK-Practice/logs:/fluentd/log
    ports:
      - "24224:24224"  # Fluentd 用于接收日志的端口
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Use HTTP (since SSL is disabled)
      - ELASTICSEARCH_USERNAME=james  # Pass the Elasticsearch username
      - ELASTICSEARCH_PASSWORD=1234qwer  # Pass the Elasticsearch password
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.7.1
    container_name: apm-server
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - APM_SERVER_SECRET_TOKEN=secret_token
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge
